name: 🚀 Deploy Docker App to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Clonar repositorio
        uses: actions/checkout@v3

      - name: 🔐 Login a Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 🚢 Deploy contenedor a Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ares
          slot-name: production
          images: 'DOCKER|'
'
